-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Drink_Ingredients CASCADE;
DROP TABLE IF EXISTS Drink_Tags CASCADE;
DROP TABLE IF EXISTS Tags CASCADE;
DROP TABLE IF EXISTS Ingredients CASCADE;
DROP TABLE IF EXISTS Drinks CASCADE;
DROP TABLE IF EXISTS Users CASCADE;